# Generated by Django 6.0.2 on 2026-02-28 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=255, verbose_name="Bo'lim nomi (UZ)")),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (RU)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Department Name (EN)')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_uz', models.CharField(max_length=255, verbose_name='F.I.SH (UZ)')),
                ('full_name_ru', models.CharField(max_length=255, verbose_name='Ф.И.О (RU)')),
                ('full_name_en', models.CharField(max_length=255, verbose_name='Full Name (EN)')),
                ('position_uz', models.CharField(max_length=255, verbose_name='Lavozimi (UZ)')),
                ('position_ru', models.CharField(max_length=255, verbose_name='Должность (RU)')),
                ('position_en', models.CharField(max_length=255, verbose_name='Position (EN)')),
                ('floor', models.CharField(max_length=10, verbose_name='Qavat')),
                ('room', models.CharField(max_length=10, verbose_name='Xona')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('image', models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='Rasm')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='api.department')),
            ],
        ),
    ]
