# Generated by Django 6.0.3 on 2026-03-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_uz', models.CharField(max_length=255, verbose_name='F.I.SH (UZ)')),
                ('full_name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ф.И.О (RU)')),
                ('full_name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name (EN)')),
                ('position_uz', models.CharField(max_length=255, verbose_name='Lavozimi (UZ)')),
                ('position_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность (RU)')),
                ('position_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Position (EN)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='leadership/', verbose_name='Rasm')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Rahbariyat',
                'verbose_name_plural': 'Rahbariyat',
                'ordering': ['order'],
            },
        ),
    ]
