# Generated by Django 6.0.2 on 2026-03-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_leadership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Rasm URL'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Rasm URL'),
        ),
    ]
