# Generated by Django 6.0.2 on 2026-03-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_employee_image_alter_leadership_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadership',
            name='rank_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rank (EN)'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='rank_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Звание (RU)'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='rank_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Darajasi (UZ)'),
        ),
    ]
