# Generated by Django 6.0.2 on 2026-03-12 11:43

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_leadership_rank_en_leadership_rank_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=api.models.SupabaseStorage(), upload_to='employees/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=api.models.SupabaseStorage(), upload_to='leadership/', verbose_name='Rasm'),
        ),
    ]
