# Generated by Django 6.0.3 on 2026-03-14 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_employee_image_alter_leadership_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadership',
            options={},
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='full_name_en',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='full_name_ru',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='position_en',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='position_ru',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='position_uz',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='rank_en',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='rank_ru',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='rank_uz',
        ),
    ]
