# Generated by Django 6.0.3 on 2026-03-15 07:17

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_leadership_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['order', 'name_uz'], 'verbose_name': "Bo'lim", 'verbose_name_plural': "Bo'limlar"},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['department__order', 'order', 'full_name_uz'], 'verbose_name': 'Xodim', 'verbose_name_plural': 'Xodimlar'},
        ),
        migrations.AlterModelOptions(
            name='leadership',
            options={'ordering': ['order'], 'verbose_name': 'Rahbariyat', 'verbose_name_plural': 'Rahbariyat'},
        ),
        migrations.AddField(
            model_name='department',
            name='order',
            field=models.PositiveIntegerField(default=100, verbose_name="Bo'lim tartibi"),
        ),
        migrations.AddField(
            model_name='employee',
            name='order',
            field=models.PositiveIntegerField(default=100, verbose_name="Bo'lim ichidagi tartib"),
        ),
        migrations.AddField(
            model_name='leadership',
            name='full_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name (EN)'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='full_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ф.И.О (RU)'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='position_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Position (EN)'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='position_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность (RU)'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='position_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lavozimi (UZ)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='floor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Qavat'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=api.models.SupabaseStorage(), upload_to='employees', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='room',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Xona'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=api.models.SupabaseStorage(), upload_to='leadership', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib raqami'),
        ),
    ]
