# Generated by Django 6.0.3 on 2026-03-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_department_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadership',
            name='email',
            field=models.EmailField(default='info@proacademy.uz', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='phone',
            field=models.CharField(default='+998712020496', max_length=25, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='rank_en',
            field=models.CharField(default='Senior Justice Advisor', max_length=100, verbose_name='Rank (EN)'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='rank_ru',
            field=models.CharField(default='Старший советник юстиции', max_length=100, verbose_name='Звание (RU)'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='rank_uz',
            field=models.CharField(choices=[('Adliya katta maslahatchisi', 'Adliya katta maslahatchisi'), ('Adliya maslahatchisi', 'Adliya maslahatchisi'), ('Adliya general-mayori', 'Adliya general-mayori'), ('1-darajali adliya maslahatchisi', '1-darajali adliya maslahatchisi'), ('2-darajali adliya maslahatchisi', '2-darajali adliya maslahatchisi')], default='Adliya katta maslahatchisi', max_length=100, verbose_name='Unvoni (UZ)'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='work_hours_ru',
            field=models.CharField(default='Каждый рабочий день 09:00-18:00', max_length=100, verbose_name='График работы (RU)'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='work_hours_uz',
            field=models.CharField(default='Har ish kuni 09:00-18:00', max_length=100, verbose_name='Ish vaqti (UZ)'),
        ),
    ]
