# Generated by Django 6.0.3 on 2026-03-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_leadership_email_leadership_phone_leadership_rank_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadership',
            name='rank_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rank (EN)'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='rank_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Звание (RU)'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='rank_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Unvoni (UZ)'),
        ),
    ]
