# Generated by Django 6.0.3 on 2026-03-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_leadership_rank_en_alter_leadership_rank_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadership',
            name='work_hours_en',
            field=models.CharField(default='Every working day 09:00-18:00', max_length=100, verbose_name='Work hours (EN)'),
        ),
    ]
